// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../../../../../src/app_repository/source/database/model/local_image_url_data.dart';
import '../../../../../src/app_repository/source/database/model/local_user_data.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 3672040623727277922),
      name: 'LocalImageUrlData',
      lastPropertyId: const obx_int.IdUid(4, 16270684668609078),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6652773689708391768),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6562328979355024874),
            name: 'large',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3401209784626881285),
            name: 'medium',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 16270684668609078),
            name: 'thumbnail',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 2237696338784524511),
      name: 'LocalUserData',
      lastPropertyId: const obx_int.IdUid(6, 6407234527801026750),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2910060366481561378),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8337991818897296143),
            name: 'email',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1832204204774810758),
            name: 'money',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 927951117496784950),
            name: 'gender',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3122642623375920159),
            name: 'birthday',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6407234527801026750),
            name: 'avatarId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(1, 1332288571790052002),
            relationTarget: 'LocalImageUrlData')
      ],
      relations: <obx_int.ModelRelation>[
        obx_int.ModelRelation(
            id: const obx_int.IdUid(1, 1987275612854619647),
            name: 'photos',
            targetId: const obx_int.IdUid(1, 3672040623727277922))
      ],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 2237696338784524511),
      lastIndexId: const obx_int.IdUid(1, 1332288571790052002),
      lastRelationId: const obx_int.IdUid(1, 1987275612854619647),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    LocalImageUrlData: obx_int.EntityDefinition<LocalImageUrlData>(
        model: _entities[0],
        toOneRelations: (LocalImageUrlData object) => [],
        toManyRelations: (LocalImageUrlData object) => {},
        getId: (LocalImageUrlData object) => object.id,
        setId: (LocalImageUrlData object, int id) {
          object.id = id;
        },
        objectToFB: (LocalImageUrlData object, fb.Builder fbb) {
          final largeOffset =
              object.large == null ? null : fbb.writeString(object.large!);
          final mediumOffset =
              object.medium == null ? null : fbb.writeString(object.medium!);
          final thumbnailOffset = object.thumbnail == null
              ? null
              : fbb.writeString(object.thumbnail!);
          fbb.startTable(5);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, largeOffset);
          fbb.addOffset(2, mediumOffset);
          fbb.addOffset(3, thumbnailOffset);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final largeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final mediumParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final thumbnailParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final object = LocalImageUrlData(
              large: largeParam, medium: mediumParam, thumbnail: thumbnailParam)
            ..id =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);

          return object;
        }),
    LocalUserData: obx_int.EntityDefinition<LocalUserData>(
        model: _entities[1],
        toOneRelations: (LocalUserData object) => [object.avatar],
        toManyRelations: (LocalUserData object) => {
              obx_int.RelInfo<LocalUserData>.toMany(1, object.id!):
                  object.photos
            },
        getId: (LocalUserData object) => object.id,
        setId: (LocalUserData object, int id) {
          object.id = id;
        },
        objectToFB: (LocalUserData object, fb.Builder fbb) {
          final emailOffset =
              object.email == null ? null : fbb.writeString(object.email!);
          final moneyOffset =
              object.money == null ? null : fbb.writeString(object.money!);
          final genderOffset =
              object.gender == null ? null : fbb.writeString(object.gender!);
          fbb.startTable(7);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, emailOffset);
          fbb.addOffset(2, moneyOffset);
          fbb.addOffset(3, genderOffset);
          fbb.addInt64(4, object.birthday);
          fbb.addInt64(5, object.avatar.targetId);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final emailParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final moneyParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final genderParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final birthdayParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final object = LocalUserData(
              email: emailParam,
              money: moneyParam,
              gender: genderParam,
              birthday: birthdayParam)
            ..id =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);
          object.avatar.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          object.avatar.attach(store);
          obx_int.InternalToManyAccess.setRelInfo<LocalUserData>(object.photos,
              store, obx_int.RelInfo<LocalUserData>.toMany(1, object.id!));
          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [LocalImageUrlData] entity fields to define ObjectBox queries.
class LocalImageUrlData_ {
  /// See [LocalImageUrlData.id].
  static final id =
      obx.QueryIntegerProperty<LocalImageUrlData>(_entities[0].properties[0]);

  /// See [LocalImageUrlData.large].
  static final large =
      obx.QueryStringProperty<LocalImageUrlData>(_entities[0].properties[1]);

  /// See [LocalImageUrlData.medium].
  static final medium =
      obx.QueryStringProperty<LocalImageUrlData>(_entities[0].properties[2]);

  /// See [LocalImageUrlData.thumbnail].
  static final thumbnail =
      obx.QueryStringProperty<LocalImageUrlData>(_entities[0].properties[3]);
}

/// [LocalUserData] entity fields to define ObjectBox queries.
class LocalUserData_ {
  /// See [LocalUserData.id].
  static final id =
      obx.QueryIntegerProperty<LocalUserData>(_entities[1].properties[0]);

  /// See [LocalUserData.email].
  static final email =
      obx.QueryStringProperty<LocalUserData>(_entities[1].properties[1]);

  /// See [LocalUserData.money].
  static final money =
      obx.QueryStringProperty<LocalUserData>(_entities[1].properties[2]);

  /// See [LocalUserData.gender].
  static final gender =
      obx.QueryStringProperty<LocalUserData>(_entities[1].properties[3]);

  /// See [LocalUserData.birthday].
  static final birthday =
      obx.QueryIntegerProperty<LocalUserData>(_entities[1].properties[4]);

  /// See [LocalUserData.avatar].
  static final avatar =
      obx.QueryRelationToOne<LocalUserData, LocalImageUrlData>(
          _entities[1].properties[5]);

  /// see [LocalUserData.photos]
  static final photos =
      obx.QueryRelationToMany<LocalUserData, LocalImageUrlData>(
          _entities[1].relations[0]);
}
