name: english_app_user

packages:
  - ./**

command:
  bootstrap:
    runPubGetInParallel: false

scripts:
  # build runner build
  build_all:
    run: dart pub global run melos exec --depends-on="build_runner" "flutter packages pub run build_runner build"
    description: build_runner build all modules.
  l10n:
    run: dart pub global run melos exec --fail-fast --scope="*localization*" --flutter -- flutter pub run intl_utils:generate
    description: Generates l10n for all app packages.
  force_build_all:
    run: dart pub global run melos exec --depends-on="build_runner" "flutter packages pub run build_runner build --delete-conflicting-outputs"
    description: build_runner build all modules.
  force_build_app:
    run: dart pub global run melos exec --fail-fast --scope="*app*" --depends-on="build_runner" "flutter packages pub run build_runner build --delete-conflicting-outputs"
    description: build_runner build app module.
  force_build_logic:
    run: dart pub global run melos exec --fail-fast --scope="*logic*" --depends-on="build_runner" "flutter packages pub run build_runner build --delete-conflicting-outputs"
    description: build_runner watch logic module.
  force_build_data:
    run: dart pub global run melos exec --fail-fast --scope="*data*" --depends-on="build_runner" "flutter packages pub run build_runner build --delete-conflicting-outputs"
    description: build_runner watch data module.
  build:apk:
    run: |
      cd app
      flutter build apk --release
    description: "Build the release APK from the app module"
