name: services
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  android_id: ^0.4.0
  decimal: ^3.0.2
  device_info_plus: ^10.1.2
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_udid: ^3.0.0
  freezed_annotation: ^2.4.4
  injectable: ^2.4.2
  get_it: ^7.7.0
  intl: ^0.19.0
  mime: ^1.0.6
  path_provider: ^2.1.4
  rxdart: ^0.28.0
  timezone: ^0.9.4
  package_info_plus: ^8.0.2
  firebase_messaging: ^15.1.2
  logic:
    path: ../logic
  flutter_local_notifications: ^17.2.3
  design:
    path: ../design

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.5.7
  injectable_generator: ^2.6.2
  build_runner: ^2.4.12

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
