name: Android CI/CD
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Upload apk to App Tester
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission to gradlew
        run: chmod +x app/android/gradlew
      - name: Build release
        run: |
          cd app/android
          ./gradlew assembleRelease
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: app/android/app/build/outputs/apk/release/app-release-unsigned.apk

  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission to gradlew
        run: chmod +x app/android/gradlew
      - name: Build debug APK
        run: |
          cd app/android
          ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app/android/app/build/outputs/apk/debug/app-debug.apk
