name: Android CI/CD
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Upload apk to App Tester
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.1
          channel: stable
      - name: Install melos
        run: flutter pub global activate melos
      - name: Install dependencies & build
        run: |
          melos bootstrap
          melos force_build_all
      - name: Recreate release-key.jks
        run: |
          echo "$JKS_BASE64" | base64 --decode > app/android/release-key.jks
        env:
          JKS_BASE64: ${{ secrets.KEY_BASE_64 }}
      - name: Build APK
        run: |
          cd app
          flutter build apk --release
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{secrets.CREDENTIALS_FILE_CONTENT}}
          groups: qa_group
          file: app/build/app/outputs/apk/release/app-release.apk
          releaseNotes: "${{ github.event.head_commit.message }}"